def main():
    return "foo"


def failure():
    raise RuntimeError("This is an error")
